# Generated by Django 4.2.6 on 2023-12-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=50)),
                ('filter_code', models.CharField(max_length=50)),
                ('filter_column', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name', models.CharField(max_length=50)),
                ('kpi_code', models.CharField(max_length=50)),
                ('kpi_section', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=50)),
                ('link', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('filter', models.ManyToManyField(to='app.filter')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_name', models.CharField(max_length=50)),
                ('persona_code', models.CharField(max_length=50)),
                ('persona_description', models.TextField()),
                ('filters', models.ManyToManyField(to='app.filter')),
                ('kpis', models.ManyToManyField(to='app.kpi')),
            ],
        ),
    ]
